/*! ****************************************************************************
 * Easing v0.0.4
 *
 * A simple library that implements Robert Penner's easing equations.
 * (you can download it from npm or github repositories)
 * Copyright (c) 2020 Mobilabs <contact@mobilabs.fr> (http://www.mobilabs.fr).
 * Released under the MIT license. You may obtain a copy of the License
 * at: http://www.opensource.org/licenses/mit-license.php).
 * Built from ES6lib v1.0.0-beta.6.
 * ************************************************************************** */
const $__ES6GLOB={};!function(t,e){"use strict";"function"==typeof define&&define.amd?define([""],e):"object"==typeof exports?module.exports=e(t):t.Easing=e(t)}($__ES6GLOB,t=>{"use strict";let e;return function(){const a=t.Easing;e={noConflict(){return t.Easing=a,this},linear:(t,e,a,s)=>a*t/s+e,swing:(t,e,a,s)=>a*(.5-Math.cos(t/s*Math.PI)/2)+e,easeInSine:(t,e,a,s)=>-a*Math.cos(t/s*(Math.PI/2))+a+e,easeOutSine:(t,e,a,s)=>a*Math.sin(t/s*(Math.PI/2))+e,easeInOutSine:(t,e,a,s)=>-a/2*(Math.cos(Math.PI*t/s)-1)+e,easeInQuad:(t,e,a,s)=>a*(t/=s)*t+e,easeOutQuad:(t,e,a,s)=>-a*(t/=s)*(t-2)+e,easeInOutQuad:(t,e,a,s)=>(t/=s/2)<1?a/2*t*t+e:-a/2*(--t*(t-2)-1)+e,easeInCubic:(t,e,a,s)=>a*(t/=s)*t*t+e,easeOutCubic:(t,e,a,s)=>a*((t=t/s-1)*t*t+1)+e,easeInOutCubic:(t,e,a,s)=>(t/=s/2)<1?a/2*t*t*t+e:a/2*((t-=2)*t*t+2)+e,easeInQuart:(t,e,a,s)=>a*(t/=s)*t*t*t+e,easeOutQuart:(t,e,a,s)=>-a*((t=t/s-1)*t*t*t-1)+e,easeInOutQuart:(t,e,a,s)=>(t/=s/2)<1?a/2*t*t*t*t+e:-a/2*((t-=2)*t*t*t-2)+e,easeInQuint:(t,e,a,s)=>a*(t/=s)*t*t*t*t+e,easeOutQuint:(t,e,a,s)=>a*((t=t/s-1)*t*t*t*t+1)+e,easeInOutQuint:(t,e,a,s)=>(t/=s/2)<1?a/2*t*t*t*t*t+e:a/2*((t-=2)*t*t*t*t+2)+e,easeInExpo:(t,e,a,s)=>0===t?e:a*Math.pow(2,10*(t/s-1))+e,easeOutExpo:(t,e,a,s)=>t===s?e+a:a*(1-Math.pow(2,-10*t/s))+e,easeInOutExpo:(t,e,a,s)=>0===t?e:t===s?e+a:(t/=s/2)<1?a/2*Math.pow(2,10*(t-1))+e:a/2*(2-Math.pow(2,-10*--t))+e,easeInCirc:(t,e,a,s)=>-a*(Math.sqrt(1-(t/=s)*t)-1)+e,easeOutCirc:(t,e,a,s)=>a*Math.sqrt(1-(t=t/s-1)*t)+e,easeInOutCirc:(t,e,a,s)=>(t/=s/2)<1?-a/2*(Math.sqrt(1-t*t)-1)+e:a/2*(Math.sqrt(1-(t-=2)*t)+1)+e,easeInBack:(t,e,a,s,n)=>(void 0===n&&(n=1.70158),a*(t/=s)*t*((n+1)*t-n)+e),easeOutBack:(t,e,a,s,n)=>(void 0===n&&(n=1.70158),a*((t=t/s-1)*t*((n+1)*t+n)+1)+e),easeInOutBack:(t,e,a,s,n)=>(void 0===n&&(n=1.70158),(t/=s/2)<1?a/2*(t*t*((1+(n*=1.525))*t-n))+e:a/2*((t-=2)*t*((1+(n*=1.525))*t+n)+2)+e),easeInElastic(t,e,a,s){var n=1.70158,u=0,i=a;return 0===t?e:1==(t/=s)?e+a:(u||(u=.3*s),i<Math.abs(a)?(i=a,n=u/4):n=u/(2*Math.PI)*Math.asin(a/i),-i*Math.pow(2,10*(t-=1))*Math.sin((t*s-n)*(2*Math.PI)/u)+e)},easeOutElastic(t,e,a,s){var n=1.70158,u=0,i=a;return 0===t?e:1==(t/=s)?e+a:(u||(u=.3*s),i<Math.abs(a)?(i=a,n=u/4):n=u/(2*Math.PI)*Math.asin(a/i),i*Math.pow(2,-10*t)*Math.sin((t*s-n)*(2*Math.PI)/u)+a+e)},easeInOutElastic(t,e,a,s){var n=1.70158,u=0,i=a;return 0===t?e:2==(t/=s/2)?e+a:(u||(u=s*(.3*1.5)),i<Math.abs(a)?(i=a,n=u/4):n=u/(2*Math.PI)*Math.asin(a/i),t<1?i*Math.pow(2,10*(t-=1))*Math.sin((t*s-n)*(2*Math.PI)/u)*-.5+e:i*Math.pow(2,-10*(t-=1))*Math.sin((t*s-n)*(2*Math.PI)/u)*.5+a+e)},easeInBounce(t,e,a,s){return a-this.easeOutBounce(s-t,0,a,s)+e},easeOutBounce:(t,e,a,s)=>(t/=s)<1/2.75?a*(7.5625*t*t)+e:t<2/2.75?a*(7.5625*(t-=1.5/2.75)*t+.75)+e:t<2.5/2.75?a*(7.5625*(t-=2.25/2.75)*t+.9375)+e:a*(7.5625*(t-=2.625/2.75)*t+.984375)+e,easeInOutBounce(t,e,a,s){return t<s/2?.5*this.easeInBounce(2*t,0,a,s)+e:.5*this.easeOutBounce(2*t-s,0,a,s)+.5*a+e}},e.VERSION="0.0.4"}(),e});export default $__ES6GLOB.Easing;